name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master


# Borrowing from https://github.com/zopefoundation/meta/blob/master/config/default/tests.yml.j2
jobs:
  build:

    strategy:
      matrix:
        config:
        - [3.6, "py36"]
        - [3.7, "py37"]
        - [3.8, "py38"]
        - [3.9, "py39"]
        # Only lint once
        - [3.6, "flake8"]
        - [3.6, "black-check"]

    runs-on: ubuntu-latest
    name: ${{ matrix.config[1] }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config[0] }}

    - name: Pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.config[0] }}-${{ hashFiles('setup.*', 'tox.ini', 'tests/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.config[0] }}-
          ${{ runner.os }}-pip-

    - name: Install tox
      run: |
        python -m pip install -U pip
        pip install tox

    - name: Run Tox
      run: tox -e ${{ matrix.config[1] }}
